kind = "mobile"
previewPath = "/mobile/"
title = "Anti-Cheat App"
version = "1.0.0"
id = "artifacts/anticheat-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/mobile/" ]
localPort = 24567

[services.development]
run = "pnpm --filter @workspace/anticheat-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/anticheat-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/anticheat-app", "run", "serve" ]

[services.env]
PORT = "24567"
BASE_PATH = "/mobile/"
